version: '3'
services:

    pythonapp:
        build: ./python/
        command: sh -c "sleep 10s ; python3 scripts/ingestion.py"
        depends_on:
            - mysql
        volumes:
            - ./python/logs:/usr/src/python-app/logs
            - ./python/data:/usr/src/python-app/data

    mysql:
        restart: always
        build: ./mysql/
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db